# World
WIDTH = 1200
HEIGHT = 800
FPS_SIMULATION = 30

NUM_FOOD_INITIAL = 100
NUM_AGENTS_INITIAL = 10

# Agent
AGENT_RADIUS = 10
AGENT_FORCE = 10000
TURN_SPEED = 2.0
DRAG_CONST_COEFF = 5
DRAG_LINEAR_COEFF = 0.05
DRAG_QUADRATIC_COEFF = 0.005

N_RANGEFINDERS = 3
RANGEFINDER_RADIUS = 150
RANGEFINDER_ANGLE = 100

NETWORK_EVALUATION_STEP = 1
N_INPUTS = N_RANGEFINDERS * 4  # distance, red, green, blue
INPUT_NAMES = [[f"D{i}", f"R{i}", f"G{i}", f"B{i}"] for i in range(N_RANGEFINDERS)]
INPUT_NAMES = [name for group in INPUT_NAMES for name in group]
OUTPUT_NAMES = ["A", "R"]  # accelerate, rotate

MAX_ENERGY = 100.0
ENERGY_DECAY = 6.0 * NETWORK_EVALUATION_STEP
ENERGY_PER_FOOD = 25.0

# Food
FOOD_SPAWN_INTERVAL = 0.1  # seconds simulation time
FOOD_RADIUS = 5
FOOD_MIN_DIST = 50

# Walls
NUM_WALLS = 50
WALL_MIN_LEN = 50
WALL_MAX_LEN = 200
WALL_THICKNESS = 5
WALL_ELASTICITY = 0.8
WALL_FRICTION = 0.8

# Colors and colors seen by agents
AGENT_COLOR = (0, 0, 255)
AGENT_SIGHT_COLOR = (0.0, 0.0, 1.0)
FOOD_COLOR = (0, 255, 0)
FOOD_SIGHT_COLOR = (0.0, 1.0, 0.0)
WALL_COLOR = (255, 0, 0)
WALL_SIGHT_COLOR = (1.0, 0.0, 0.0)

# Colors
BACKGROUND_COLOR = (30, 30, 30)
FACING_COLOR = (0, 0, 255)
RAY_COLOR = (0, 255, 255)

# Misc
INFO_INTERVAL = 5  # seconds simulation time
FPS_VISUALIZATION = 60  # max visualization FPS
